version: '3.8'

services:
  app:
    build: .
    container_name: java_app
    ports:
      - "8083:8083"
    depends_on:
      - db
    environment:
      - DB_URL=jdbc:postgresql://db:5432/mydatabase
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    restart: unless-stopped

  db:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydatabase
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=12345
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped

  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    ports:
      - "8087:80"
    volumes:
      - .:/srv
      - .:/database/filebrowser.db
      - .:/config/settings.json
    environment:
      - FB_BASEURL=/filebrowser
    restart: unless-stopped

volumes:
  pg_data:
    driver: local
  pgadmin_data:
    driver: local

